### ISSUE TITLE
Where is Bellevue/Redmond? - gives gym information

### ISSUE THREAD

**Issue by alyssaw90** [alyssaw90/Relo-Chatbot#56]
"Where is Bellevue?" returns information about ProClub.

"Where is Redmond" returns [The ProClub https://www.proclub.com/ is a few minutes from the north campus, and here is a link to other gyms in the area http://www.yelp.com/search?cflt=gyms&find_loc=Redmond%2C+WA]

Should return a link to map of where the city is, but should only give answers about Seattle, Bellevue, Redmond. If another city is asked about tell them that questions cannot be answered.

**Comment by MarySam** [comment]
Finished adding utterances in Luis, Yueyue is adding the "GetAddress" case in CommuteBot.
