### ISSUE TITLE
Lodging Questions

### ISSUE THREAD

**Issue by alyssaw90** [alyssaw90/Relo-Chatbot#7]

**Comment by qwergram** [comment]
Zillow API: http://www.zillow.com/howto/api/GetUpdatedPropertyDetails.htm

API is pretty limited unless we have an exact address.

**Comment by qwergram** [comment]
We should cache results from the API for 12 hours to prevent being banned from the Zillow API. We can either do this by storing the results in a database, or we could just store it as local variables. That being said, I vote for database. Requiring a SQL database somehow.

**Comment by qwergram** [comment]
Forrent Website: https://www.forrent.com/calculator
The links that it redirects you to are in the following format:
`https://www.forrent.com/find/<STATE_CODE>/<BUS_SYSTEM>/<CITY>/price-Less+than+<PRICE>`
For example: `https://www.forrent.com/find/WA/metro-Seattle/Redmond/price-Less+than+2000`

**Comment by jennyf19** [comment]
See GitHub Wiki for topics ideas from the LEAP members
